### ISSUE TITLE
ImportError: No module named error

### ISSUE THREAD

**Issue by n1nj4888** [barrycarey/Plex-Data-Collector-For-InfluxDB#19]
I'm trying to run the plexcollector.py from the command line but am getting the following error - Could it be that I'm missing a dependency here (I did run pip install "pip install -r requirements.txt"):

```
<USER>@ubuntu18-vm:~/scripts/Plex-Data-Collector-For-InfluxDB$ python plexcollector.py
Traceback (most recent call last):
  File "plexcollector.py", line 3, in <module>
    from plexcollector.PlexInfluxdbCollector import PlexInfluxdbCollector
  File "/home/<USER>/scripts/Plex-Data-Collector-For-InfluxDB/plexcollector/PlexInfluxdbCollector.py", line 5, in <module>
    from urllib.error import HTTPError
ImportError: No module named error
```

**Comment by azlux** [comment]
Hi @n1nj4888 ,
Can you give us the output of : `python -V`
I think you use python2 instead of python3.

**Comment by n1nj4888** [comment]
“python -V” returns “Python 2.7.15rc1” so thanks for pointing that out. 

If I now run ```python3 plexCollector.py``` I get the following errors:

```
<USER>@ubuntu18-vm:~/scripts/Plex-Data-Collector-For-InfluxDB$ python3 plexcollector.py 
Loading config: config.ini
Traceback (most recent call last):
  File "/home/<USER>/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/<USER>/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/<USER>/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<USER>/.local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/<USER>/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/<USER>/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/<USER>/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/<USER>/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/<USER>/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/<USER>/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "plexcollector.py", line 3, in <module>
    from plexcollector.PlexInfluxdbCollector import PlexInfluxdbCollector
  File "/home/<USER>/scripts/Plex-Data-Collector-For-InfluxDB/plexcollector/PlexInfluxdbCollector.py", line 14, in <module>
    from plexcollector.common import log
  File "/home/<USER>/scripts/Plex-Data-Collector-For-InfluxDB/plexcollector/common/__init__.py", line 1, in <module>
    from .utils import log
  File "/home/<USER>/scripts/Plex-Data-Collector-For-InfluxDB/plexcollector/common/utils.py", line 5, in <module>
    from plexcollector.config import config
  File "/home/<USER>/scripts/Plex-Data-Collector-For-InfluxDB/plexcollector/config/__init__.py", line 10, in <module>
    config = ConfigManager(config)
  File "/home/<USER>/scripts/Plex-Data-Collector-For-InfluxDB/plexcollector/config/configmanager.py", line 23, in __init__
    self._validate_plex_servers()
  File "/home/<USER>/scripts/Plex-Data-Collector-For-InfluxDB/plexcollector/config/configmanager.py", line 67, in _validate_plex_servers
    r = requests.get(server_url, verify=self.plex_verify_ssl)
  File "/home/<USER>/.local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/<USER>/.local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/<USER>/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/<USER>/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/<USER>/.local/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
<USER>@ubuntu18-vm:~/scripts/Plex-Data-Collector-For-InfluxDB$ 
```

**Comment by barrycarey** [comment]
It looks like it's failing to connect to the Plex server.  Although I'm not sure why the exception isn't being caught.  I haven't actually tested on Linux. 

Double check your plex server address.  Make sure you put it in without the port or http.  It should be a straight IP address or hostname.

**Comment by azlux** [comment]
You can try with a curl command, and check the server answer:
` curl <IP or domain here>:32400`
if success you will have : 
`<html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>`

**Comment by n1nj4888** [comment]
I get the following strange result from curl from two computers on the same internal network as the Plex server - The second server is the Plex server itself.

Plex server is up and working as expected - Plex.tv web app shows the server as being fully remotely accessible so not sure why it is not responding to the curl request? Could this be due to a setting on the server (secure connections perhaps?)

```
<USER>@ubuntu18-vm:~$ curl 192.168.1.254:32400
curl: (52) Empty reply from server
<USER>@ubuntu18-vm:~$ curl https://192.168.1.254:32400
curl: (51) SSL: no alternative certificate subject name matches target host name '192.168.1.254'
```

**Comment by n1nj4888** [comment]
To update on this, it seems that the Plex Server is not responding to calls to the internal IP address of 192.168.1.254:32400 but does respond to a curl request to localhost:32400 on the server itself

**Running a curl request to 192.168.1.254 (from the same 192.168.1.254 server):**
```
curl 192.168.1.254:32400
curl: (52) Empty reply from server
```

**Running a curl request to localhost (from the same 192.168.1.254 server):**
```
curl localhost:32400
<html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```

Checking the Plex Debug logs, the curl requests to the internal IP address of the server (192.168.1.254) from the exact same server shows that the request is being denied because Secure Connections are set to "Required" in the Plex Server config... 

```
DEBUG - Request: [192.168.1.254:58775] rejected because secure connections are required
```

The request is accepted if the ```curl localhost:32400``` is run presumably because localhost doesn't require a secure connection.

If this is the case, does the plexconnector.py script work if secure connections are enabled and required on the Plex Server? For example, is there some option I have to set in config for the script to work when communicating to a server with secure connections set as required?

Thanks!

**Comment by barrycarey** [comment]
Under the Plex section of the config try setting HTTPS = True and Verify_SSL = False

If you have Secure Connection required on the plex server this tool needs to have HTTPS set to true.  If you are using a self sign SSL Verify_SSL needs to be false.

**Comment by n1nj4888** [comment]
> Under the Plex section of the config try setting HTTPS = True and Verify_SSL = False
> 
> If you have Secure Connection required on the plex server this tool needs to have HTTPS set to true. If you are using a self sign SSL Verify_SSL needs to be false.

Thanks!

Yes, I've got Secure Connections set as "Required" on the Plex Server - There doesn't seem to be a way in Plex of having Secure Connections as "Required" but allowing specified local hosts to connect insecure? 

With HTTPS = True and Verify_SSL = False, I now get the following output so making progress hopefully!

```
<USER>@ubuntu18-vm:~/scripts/Plex-Data-Collector-For-InfluxDB$ python3 plexcollector.py
Loading config: config.ini
/home/<USER>/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Unexpected status code 200 from Plex server
INFO: Found 0 Bad Server(s).  Removing Them From List
Configuration Successfully Loaded
Traceback (most recent call last):
  File "plexcollector.py", line 9, in <module>
    collector.run()
  File "/home/<USER>/scripts/Plex-Data-Collector-For-InfluxDB/plexcollector/PlexInfluxdbCollector.py", line 392, in run
    self.get_recently_added()
  File "/home/<USER>/scripts/Plex-Data-Collector-For-InfluxDB/plexcollector/PlexInfluxdbCollector.py", line 316, in get_recently_added
    recent_list += server.library.section('Music').search(sort='addedAt:desc', libtype='track', maxresults=10)
  File "/home/<USER>/.local/lib/python3.6/site-packages/plexapi/library.py", line 55, in section
    raise NotFound('Invalid library section: %s' % title)
plexapi.exceptions.NotFound: Invalid library section: Music
```

Looks like an exception is now being thrown because there is no Music library - This is true since I don't have any Music Libraries configured on the server... Is there a config.ini option to ignore specific Library Types?

**Comment by azlux** [comment]
Fix into #21

**Comment by barrycarey** [comment]
Merged the fix.  Give it a shot now.

**Comment by benderstwin** [comment]
Assuming there isnt' a way to use this if you have home users with pin set up?  I just get an Authorized response"
