### ISSUE TITLE
No module named error

### ISSUE THREAD

**Issue by mkono87** [barrycarey/Plex-Data-Collector-For-InfluxDB#29]
Also getting this issue but the earlier issue posted I was unable to find a solution

**Comment by Sorensiim** [comment]
Yep, me too.

**Comment by RetroDadson** [comment]
How are you trying to run this? in Docker or just as a normal python script?

**Comment by Sorensiim** [comment]
Python on a Debian VM.

**Comment by RetroDadson** [comment]
python 3?

**Comment by Sorensiim** [comment]
Yarp.

**Comment by RetroDadson** [comment]
Have you run this to install all module requirements? 
`pip install -r requirements.txt`
I just tested on my windows machine and this was all that was needed to resolve it.

**Comment by Sorensiim** [comment]
Yes.

I'll give it a whirl on a Windows machine later.

**Comment by mkono87** [comment]
I just use varken instead of this now works great.

**Comment by Sorensiim** [comment]
Works just fine on Windows, still getting the same error on Linux .

@mkono87 why did you close this? The issue is still very much there.

**Comment by mkono87** [comment]
@Sorensiim I posted this issue 11 months ago and its not "my" issue anymore. Can you not just make a new one?

**Comment by RetroDadson** [comment]
try running pip3 instead of pip `pip3 install -r requirements.txt`

**Comment by barrycarey** [comment]
@Sorensiim Can you give me the whole trace? 

I haven't look at this project in a long time.  But last time I did I was developing on Ubuntu.

**Comment by agneevX** [comment]
Still facing the same issue :(
```
pi@pi4:/opt/Plex-Data-Collector-For-InfluxDB $ python ./plexcollector.py 
Traceback (most recent call last):
  File "./plexcollector.py", line 3, in <module>
    from plexcollector.PlexInfluxdbCollector import PlexInfluxdbCollector
  File "/opt/Plex-Data-Collector-For-InfluxDB/plexcollector/PlexInfluxdbCollector.py", line 5, in <module>
    from urllib.error import HTTPError
ImportError: No module named error

```

**Comment by StickyzzG** [comment]
in my case i was using a pi 4  so it was defaulting to python 2.7
I needed to change the line ExecStart=/usr/bin/python to ExecStart=/usr/bin/python3.7
Then all worked fine
