### ISSUE TITLE
index out of range after starting a stream

### ISSUE THREAD

**Issue by gregflynn** [barrycarey/Plex-Data-Collector-For-InfluxDB#31]
```
$ python plexcollector.py --singlerun
Loading config: config.ini
INFO: Found 0 Bad Server(s).  Removing Them From List
Configuration Successfully Loaded
Traceback (most recent call last):
  File "plexcollector.py", line 9, in <module>
    collector.run()
  File "/opt/Plex-Data-Collector-For-InfluxDB/plexcollector/PlexInfluxdbCollector.py", line 394, in run
    self.get_active_streams()
  File "/opt/Plex-Data-Collector-For-InfluxDB/plexcollector/PlexInfluxdbCollector.py", line 154, in get_active_streams
    self._process_active_streams(active_streams)
  File "/opt/Plex-Data-Collector-For-InfluxDB/plexcollector/PlexInfluxdbCollector.py", line 190, in _process_active_streams
    session_id = stream.session[0].id
IndexError: list index out of range
```

Was working fine collecting stats until I started a stream, I'll do some more digging later but wanted to post this now

**Comment by gregflynn** [comment]
Have done some more debugging, and it's weird and probably an upstream plex issue, BUT I'm only able to produce this stack trace when one of the active clients is PlexAmp. Both the web app and plex-media-player C++/Qt app work fine and properly report back a session.

**Comment by micahfocht** [comment]
I put the whole section that grabs information about which client is active inside a try statement and that works for me since I’m only displaying active users.  Maybe a stopgap solution until a proper fix can come from the plex team.
